import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
    header: {
        height: 100,
        width: '100%',
        backgroundColor: 'white',
        flexDirection: 'column',
        justifyContent: 'flex-end',
        borderColor: 'grey',
        borderBottomWidth: 1,
    },
    headerly: {
        height: 50,
        width: '100%',
        backgroundColor: 'white',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    headerbos: {
        height: 50,
        width: 90,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginLeft: 10,
    },
    lastbox: {
        height: 50,
        width: 30,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginRight: 10,
    },
    middlebox: {
        height: 50,
        width: '50%',
        flexDirection: 'column',
        backgroundColor: 'white',
        justifyContent:'center',
        marginRight: 10,
    },
    imager: {
        height: 38,
        width: 38,
        backgroundColor: '#44444450',
        borderRadius: 30,

        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    },
    image: {
        height: 35,
        width: 35,
        backgroundColor: 'white',
        borderRadius: 30,
    },
    img: {
        height: '100%',
        width: '100%',
        backgroundColor: 'white',
        borderRadius: 60,
    },
    body: {
        flex: 1,

    },

    bigtext: {
        fontSize: 20,
        fontWeight: '700',
        fontFamily: 'inter',
    },
    smalltext: {
    },
    bottomcover: {
        height: 60,
        width: '100%',
        flexDirection: 'row',
        justifyContent: 'space-around',
        position: 'absolute',
        bottom:0,
    },
    bottom: {
        height: 50,
        width: '80%',
        flexDirection: 'row',
        justifyContent: 'space-between',
        borderRadius:30,
        borderColor:'#ff5222',
        borderWidth:1,
    },
    sendcover: {
        height: 45,
        width: 45,
        backgroundColor:'#ff5222',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems:"center",
        borderRadius:30,
        borderColor:'#ff5222',
        borderWidth:1,
    },
    input:{
        height: 45,
        width: '75%',
        fontSize:20,
        marginLeft:20,
        flexDirection: 'row',
        justifyContent: 'space-between',
        borderRadius:30,
    },
})