import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
    header: {
        height: 100,
        width: '100%',
        backgroundColor: 'white',
        flexDirection: 'column',
        justifyContent: 'flex-end',
        borderColor: 'darkblue',
        borderBottomWidth: 2,
    },
    headerly: {
        height: 50,
        width: '100%',
        backgroundColor: 'white',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    headerbos: {
        height: 50,
        width: 90,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginLeft: 10,
    },
    lastbox: {
        height: 50,
        width: 30,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginRight: 10,
    },
    middlebox: {
        height: 50,
        width: '60%',
        flexDirection: 'column',
        paddingLeft: 10,
        justifyContent: 'center',
        marginRight: 10,
    },
    imager: {
        height: 38,
        width: 38,
        backgroundColor: '#ff000050',
        borderRadius: 30,

        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    },
    image: {
        height: 35,
        width: 35,
        backgroundColor: 'white',
        borderRadius: 30,
    },
    img: {
        height: '100%',
        width: '100%',
        backgroundColor: 'white',
        borderRadius: 60,
    },
    body: {
        flex: 1,

    },
    bigtext: {
        fontSize: 20,
        fontWeight: '700',
    },
    smalltext: {
        color: 'darkblue',
    },
    container: {
        marginBottom: 70,
    },
    bottomcover: {
        height: 60,
        width: '100%',
        flexDirection: 'row',
        justifyContent: 'space-around',
        position: 'absolute',
        bottom: 0,
        backgroundColor: '#f1f1f1',
    },
    bottom: {
        height: 50,
        width: '80%',
        flexDirection: 'row',
        justifyContent: 'space-around',
        borderRadius: 30,
        borderColor: '#ff5222',
        alignItems: 'center',
        borderWidth: 1,
    },
    sendcover: {
        height: 45,
        width: 50,
        flexDirection: 'row',
        borderWidth: 0,
        justifyContent: 'center',
        alignItems: "center",
        borderRadius: 10,
        borderColor:'#444444',
        borderWidth:1,
    },
    input: {
        height: 45,
        maxWidth: '65%',
        minWidth: '45%',
        fontSize: 18,
        marginLeft: 5,
        fontWeight: '500',
        flexDirection: 'row',
        justifyContent: 'space-between',
        borderRadius: 30,
        shadowRadius: 5,
        shadowColor: 'red',

    },
    messagecover: {
        width: '100%',
        height: 'auto',
        marginTop: 10,
    },
    messagebox: {
        width: 'auto',
        maxWidth: '60%',
        minWidth: '40%',
        height: 'auto',
        marginLeft: 10,
        minHeight: 50,
       
        backgroundColor: 'grey',
        alignSelf: 'flex-start',
        borderBottomLeftRadius:-25,
        borderTopLefttRadius:25,
        borderBottomRightRadius:25,
        borderTopRightRadius:25,
        justifyContent: 'center',

    },
    mybox: {
        width: 'auto',
        maxWidth: '60%',
        minWidth: '40%',
        height: 'auto',
        boxSizing:'border-box',
        minHeight: 50,
        marginRight: 10,
        backgroundColor: '#ff5222',
        alignSelf: 'flex-end',
        borderBottomRightRadius:-25,
        borderTopRightRadius:25,
        borderBottomLeftRadius:25,
        borderTopLeftRadius:25,
        justifyContent: 'center',
    },
    chatmsg: {
        fontSize: 15,
        textAlign: 'center',
        color: 'white',
        fontWeight: '500',
        paddingTop: 2,
        paddingLeft: 10,
        paddingRight: 10,
        
    },
    inboxx:{
        height: 12,
        width: 'auto',
        maxWidth: '50%',
        alignSelf:'flex-end',
        minWidth: '40%',
        backgroundColor: 'transparent',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent:'flex-end',
        marginRight:15,
        borderRadius: 25,
    },
})