import { StyleSheet } from "react-native";
export const styler = StyleSheet.create({
    previewbox: {
        flex: 1,
        backgroundColor: '#ff5212',
    },
    pretext: {
        fontSize: 60,
        fontWeight: '900',
        color: 'white',
        textAlign: 'center',
        marginTop: '90%',
        marginBottom: 0,
    },
    boxcont: {
        width: '100%',
        borderRadius: 25,
        height: 70,
        position: 'absolute',
        alignItems: 'center',
        bottom: 19,
    },
    container: {
        width: '50%',
        backgroundColor: 'white',
        borderRadius: 25,
        height: 40,
        justifyContent: 'space-between',
        paddingRight:10,
        flexDirection:'row',
        alignItems: 'center',

    },
    buttonstyle: {
        width: '60%',
        backgroundColor: '#00006f',
        borderRadius: 25,
        height: 35,
        alignItems: 'center',
        justifyContent: 'center',
        marginLeft:5,
        right: 0,
    },
    kilode: {
        color: 'white',
        fontSize: 20,
        fontWeight: '500',
    },
    free: {
        color: 'white',
        fontSize: 20,
        fontWeight: '500',
    },
    backenter: {
        flex: 1,
        backgroundColor: 'white',

    },
    mainbox: {
        flex: 1,
        marginTop: 140,
        backgroundColor: 'white',
    },
    mycontainer: {
        borderWidth: 1,
        borderColor: 'white',
        height: 150,
        alignItems: 'center',
        justifyContent: 'space-around',
        bottom: 10,
        position: 'absolute',
        width: '100%',
    },
    buttonstyler: {
        width: '70%',
        backgroundColor: 'darkblue',
        borderRadius: 25,
        height: 45,
        alignItems: 'center',
        justifyContent: 'center',
        right: 0,
    },
    buttonstylez: {
        width: '70%',
        backgroundColor: 'white',
        borderWidth: 2,
        borderColor: 'darkblue',
        borderRadius: 25,
        height: 45,
        alignItems: 'center',
        justifyContent: 'center',
        right: 0,
    },
    kiloder: {
        color: 'darkblue',
        fontSize: 20,
        fontWeight: '500',
    },
    image: {
        width: '100%',
        height: 200,
        marginTop: 50,
        borderRadius: 18,
    },
    free: {
        color: 'darkblue',
        fontSize: 35,
        fontWeight: '800',
        marginTop: 10,
        textAlign: 'center',
        fontFamily: 'sans-serif',
    },
    freer: {
        fontSize: 20,
        paddingLeft: 5,
        fontWeight: '400',
        marginTop: 10,
        textAlign: 'center',
    },
    textsmall:{
        color:'white',
        fontWeight:'600',
        paddingLeft:10,
        marginTop: 10,
    },
    creator:{
        color: 'darkblue',
        paddingLeft: 20,
        fontSize: 30,
        fontWeight: '700',
        marginTop: 120,
    },
    boxconter: {
        width: '100%',
        borderRadius: 25,
        height: 70,
        position: 'absolute',
        alignItems: 'center',
        bottom: 10,
    },
    textcont:{
        flexDirection:'row',
        justifyContent:'space-around',
        margin:0,
    },
    textsmal:{
        color:'yellow'
    }

})