import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
    inputty: {
        backgroundColor: 'white',
        borderRadius: 15,
        paddingTop: 10,
        paddingBottom: 10,
        paddingLeft: 10,
        paddingRight: 30,
        color: 'black',
        borderWidth: 1,
        borderColor: '#ffd222',
        height: 40,
        width: '80%',
    },
    smallbox: {
        backgroundColor: 'white',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 10,
        paddingTop: 10,
        paddingBottom: 10,
        borderWidth: 1,
        borderColor: '#ffd222',
        paddingLeft: 10,
        paddingRight: 30,
        color: 'white',
        height: 40,
        width: '10%',
    },
    input: {
        backgroundColor: 'white',
        borderRadius: 30,
        paddingTop: 10,
        paddingBottom: 10,
        paddingLeft: 10,
        paddingRight: 30,
        color: 'black',
        height: 40,
        width: '80%',
    },
    bigbox: {
        backgroundColor: 'white',
        height: 50,
        width: '95%',
        borderRadius: 20,
        borderWidth: 1,
        borderColor: '#ffc222',
        color: 'black',
        margin: 10,
        elevation: 2,
        flexDirection: 'row',
        justifyContent: 'space-around',
        alignItems: 'center',
    },
    biggybox: {
        backgroundColor: 'white',
        height: 50,
        width: '95%',
        borderColor: 'darkblue',
        color: 'white',
        margin: 10,
        flexDirection: 'row',
        justifyContent: 'space-around',
        alignItems: 'center',
    },
    create: {
        color: '#ff2222',
        fontSize: 30,
        fontWeight: '800',
        marginTop: 80,
        textAlign: 'center',

    },
    footname: {
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        width: '20%',
    },
    styleuna: {
        fontWeight: '700',
    },
    saves: {
        fontSize: 15,
        fontWeight: '500',
        marginBottom: 10,
        paddingLeft: 10,
    },
    hutton: {
        width: '80%',
        backgroundColor: '#ff8222',
        borderWidth: 1,
        borderColor: 'black',
        borderRadius: 25,
        height: 45,
        alignItems: 'center',
        justifyContent: 'center',
        right: 0,
    },
    press: {
        color: 'darkblue',
        fontSize: 20,
        fontWeight: '700',
    },
    previewbox: {
        flex: 1,
        backgroundColor: 'white',
    },
    pretext: {
        fontSize: 60,
        fontWeight: '800',
        fontFamily: 'sans-serif',
        color: 'white',
        textAlign: 'center',
        marginTop: '90%',
        marginBottom: 0,
    },
    boxcont: {
        width: '100%',
        borderRadius: 25,
        height: 70,
        position: 'absolute',
        alignItems: 'center',
        bottom: 19,
    },
    container: {
        width: '60%',
        backgroundColor: 'white',
        borderRadius: 25,
        height: 50,
        justifyContent: 'space-between',
        paddingRight: 10,
        flexDirection: 'row',
        alignItems: 'center',

    },
    buttonstyle: {
        width: '60%',
        backgroundColor: 'darkblue',
        borderRadius: 25,
        height: 45,
        alignItems: 'center',
        justifyContent: 'center',
        marginLeft: 5,
        right: 0,
    },
    kilode: {
        color: 'white',
        fontSize: 20,
        fontWeight: '500',
    },
    free: {
        color: 'white',
        fontSize: 20,
        fontWeight: '500',
    },
    backenter: {
        flex: 1,
        backgroundColor: 'white',

    },
    mainbox: {
        flex: 1,
        marginTop: 140,
        backgroundColor: 'white',
    },
    mycontainer: {
        borderWidth: 1,
        borderColor: 'white',
        height: 150,
        alignItems: 'center',
        justifyContent: 'space-around',
        bottom: 10,
        position: 'absolute',
        width: '100%',
    },
    buttonstyler: {
        width: '70%',
        backgroundColor: 'darkblue',
        borderRadius: 25,
        height: 45,
        alignItems: 'center',
        justifyContent: 'center',
        right: 0,
    },
    buttonstylez: {
        width: '70%',
        backgroundColor: 'white',
        borderWidth: 2,
        borderColor: '#ff5222',
        borderRadius: 25,
        height: 45,
        alignItems: 'center',
        justifyContent: 'center',
        right: 0,
    },
    kiloder: {
        color: 'darkblue',
        fontSize: 20,
        fontWeight: '500',
    },
    image: {
        width: '100%',
        height: 200,
        marginTop: 50,
        borderRadius: 18,
    },
    free: {
        color: 'darkblue',
        fontSize: 35,
        fontWeight: '800',
        marginTop: 10,
        textAlign: 'center',
        fontFamily: 'sans-serif',
    },
    freer: {
        fontSize: 20,
        paddingLeft: 5,
        fontWeight: '400',
        marginTop: 10,
        textAlign: 'center',
    },
    textsmall: {
        color: '#1c1c15',
        fontWeight: '600',
        paddingLeft: 10,
        marginTop: 10,
    },
    creator: {
        color: 'darkblue',
        paddingLeft: 20,
        fontSize: 30,
        fontWeight: '700',
        marginTop: 120,
    },
    boxconter: {
        width: '100%',
        borderRadius: 25,
        height: 70,
        marginTop: 60,
        alignItems: 'center',
    },
    textcont: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        margin: 0,
    },
    textsmals: {
        color: 'black',
        fontWeight: '700',
        fontSize: 22,
        marginLeft: 18,
        marginBottom: 10,
        marginTop: 10,
        textAlign:'center',
    },
    textsmal: {
        color: 'red'
    },
    textys: {
        color: 'darkblue',
        fontWeight: '800',
        fontSize: 20,
        textAlign:'center',
        textDecorationColor:'darkblue',
        textDecorationLine:'underline',
    },


});

